services:
  # 1. MySQL Ledger Database mapped to local port 3307
  wave-mysql:
    image: mysql:8.0
    container_name: wave-mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waveterminal
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Redis Market State Cache
  wave-redis:
    image: redis:7.0-alpine
    container_name: wave-redis-cache
    ports:
      - "6379:6379"

  # 3. RabbitMQ Message Broker
  wave-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: wave-mq-broker
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
